version: '3.8'

services:
  mysql-db-orders:
    image: mysql:latest
    container_name: bdOrders
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: Orders
      MYSQL_USER: usuarioOrders
      MYSQL_PASSWORD: passwordOrders
    ports:
      - "3307:3306"
    volumes:
      - mysql-data-orders:/var/lib/mysql

  order-service:
    image: order-service
    container_name: order-service
    build: .
    depends_on:
      - mysql-db-orders
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db-orders:3306/Orders
      SPRING_DATASOURCE_USERNAME: usuarioOrders
      SPRING_DATASOURCE_PASSWORD: passwordOrders

volumes:
  mysql-data-orders: